
# 名称
name: tag

on:
  push:
    tags: 
    - '*'

# defaults:
#   run:
#     working-directory: /usr/src/app

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: curl test
        run: |
          curl -H "Content-Type:application/json" -X POST -d '{"title": "测试", "text":"success"}' https://open.feishu.cn/open-apis/bot/hook/3e7fb607-c619-417e-ab24-a266cc04462d